---
title: "Caso 3"
author: "Joan Lamprea y José Valdés"
date: "2023-06-06"
encoding: "UTF-8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#
suppressMessages(suppressWarnings(library(gplots)))
#datos
Data <- source("yX.diabetes.train.txt") # guarda una lista
Test_data <- source("yX.diabetes.test.txt")
source("Modelo_1.R")
source("Modelo_2.R")
source("Modelo_3.R")
source("Modelo_4.R")
```

# Caso 3: Análisis de diabetes

## Datos de entrenamiento

```{r}
###### datos entrnamiento
Train_Data <- Data$value
# dimensiones
dim(Train_Data)
# seleccionando las de trabajar
Train_Data <- Train_Data[,c(1:11)]
X <- Train_Data[,c(2:11)]
y <- Train_Data[,1]
###### datos prueba
Test <- Test_data$value
# dimensiones
dim(Test)
### Seleccionando las de prueba
Test <- Test[,c(1:11)]
X_test <- Test[,c(2:11)]
y_test <- Test[,1]
```

### Analisis descriptivo

```{r}
# medias
colMeans(Train_Data)
#correlaciones
# Calcular la matriz de correlaciones
matriz_correlaciones <- cor(Train_Data)
# Crear el mapa de calor
heatmap.2(matriz_correlaciones,Colv = NA, Rowv = NA,trace = "none",
          col = colorRampPalette(c("blue", "white", "red"))(100),
          main = "Matriz de Correlaciones")
```

```{r Convergencia Modelo 1}
tictoc::tic()
set.seed(1856)
cadena_M1 <- MCMC_1(X,y,B = 10000)
tictoc::toc()

# Gr?fico
yrange <- range(cadena_M1$LP)
plot(cadena_M1$LP, type = "p", pch = 20, cex = 0.8, col = "darkblue", ylim = yrange, xlab = "Iteraci?n",ylab = "Log-verosimilitud", main = "Modelo 1")
```

```{r Convergencia Modelo 2}
tictoc::tic()
set.seed(1856)
cadena_M2 <- MCMC_2(X,y,B = 10000)
tictoc::toc()

# Gr?fico
yrange <- range(cadena_M2$LP)
plot(cadena_M2$LP, type = "p", pch = 20, cex = 0.8, col = "red", ylim = yrange, xlab = "Iteraci?n",ylab = "Log-verosimilitud", main = "Modelo 2")
```

```{r Convergencia Modelo 3}
tictoc::tic()
set.seed(1856)
cadena_M3 <- MCMC_3(X,y,B = 30000)
tictoc::toc()

# Gr?fico
yrange <- range(cadena_M3$LP)
plot(cadena_M3$LP, type = "p", pch = 20, cex = 0.8, col = "darkgreen", ylim = yrange, xlab = "Iteraci?n",ylab = "Log-verosimilitud", main = "Modelo 3")
```

```{r Convergencia Modelo 4}
tictoc::tic()
set.seed(1856)
cadena_M4 <- MCMC_4(X,y,S = 10000)
tictoc::toc()

# Gr?fico
yrange <- range(cadena_M4$LP)
plot(cadena_M4$LP, type = "p", pch = 20, cex = 0.8, col = "green", ylim = yrange, xlab = "Iteraci?n",ylab = "Log-verosimilitud", main = "Modelo 4")
```
## Tamaño efectivo de muestra

```{r}
#modelo 1
coda::effectiveSize(cadena_M1$BET)
#modelo 2
coda::effectiveSize(cadena_M2$BET)
#modelo 3
coda::effectiveSize(cadena_M3$BET)
#modelo 4
coda::effectiveSize(cadena_M4$BET)
```
## Error de monte carlo

```{r}
#modelo 1
apply(X = cadena_M1$BET, MARGIN = 2, FUN = sd)/sqrt(coda::effectiveSize(cadena_M1$BET))
#modelo 2
apply(X = cadena_M2$BET, MARGIN = 2, FUN = sd)/sqrt(coda::effectiveSize(cadena_M2$BET))
#modelo 3
apply(X = cadena_M3$BET, MARGIN = 2, FUN = sd)/sqrt(coda::effectiveSize(cadena_M3$BET))
#modelo 4
apply(X = cadena_M4$BET, MARGIN = 2, FUN = sd)/sqrt(coda::effectiveSize(cadena_M4$BET))
```

# Beta BAyes Estimados para cada modelo

```{r}
# modelo 1
Beta_M1 <- colMeans(cadena_M1$BET)
Beta_M1
# modelo 2
Beta_M2 <- colMeans(cadena_M2$BET)
Beta_M2
# modelo 3
Beta_M3 <- colMeans(cadena_M3$BET)
Beta_M3
# modelo 4
Beta_M4 <- colMeans(cadena_M4$BET)
Beta_M4
```
### intervalos de credibilidad

```{r}
# modelo 1
IC95_M1 <- NULL
for (j in 1:10) {
      ic <-quantile(cadena_M1$BET[,j], probs = c(0.025,.5,.975))
      IC95_M1 <- rbind(IC95_M1, c(ic))
      
}
IC95_M1
# modelo 2
IC95_M2 <- NULL
for (j in 1:10) {
      ic <-quantile(cadena_M2$BET[,j], probs = c(0.025,.5,.975))
      IC95_M2 <- rbind(IC95_M2, c(ic))
      
}
IC95_M2
# modelo 3
IC95_M3 <- NULL
for (j in 1:10) {
      ic <-quantile(cadena_M3$BET[,j], probs = c(0.025,.5,.975))
      IC95_M3 <- rbind(IC95_M3, c(ic))
      
}
IC95_M3
# modelo 4
IC95_M4 <- NULL
for (j in 1:10) {
      ic <-quantile(cadena_M4$BET[,j], probs = c(0.025,.5,.975))
      IC95_M4 <- rbind(IC95_M4, c(ic))
      
}
IC95_M4
```

## Preguntas

Primero los $\hat{y}$ para cada modelo
```{r}
#modelo 1
Y_pron_m1 <- X_test%*%Beta_M1
Y_pron_m1
#modelo 2
Y_pron_m2 <- X_test%*%Beta_M2
Y_pron_m2
#modelo 3
Y_pron_m3 <- X_test%*%Beta_M3
Y_pron_m3
#modelo 4
Y_pron_m4 <- X_test%*%Beta_M4
Y_pron_m4
```

### Error medio absoluto

```{r}
#modelo 1
err_abs_med_M1 <- (1/length(y_test))*sum(abs(y_test - Y_pron_m1))
err_abs_med_M1
#modelo 2
err_abs_med_M2 <- (1/length(y_test))*sum(abs(y_test - Y_pron_m2))
err_abs_med_M2
#modelo 3
err_abs_med_M3 <- (1/length(y_test))*sum(abs(y_test - Y_pron_m3))
err_abs_med_M3
#modelo 4
err_abs_med_M4 <- (1/length(y_test))*sum(abs(y_test - Y_pron_m4))
err_abs_med_M4

```

### graficos

```{r}
# graficos
par(mfrow = c(2,2))
plot(y_test,Y_pron_m1, ylim = c(-1.5,2))
abline(a = 0,b = 1)
plot(y_test,Y_pron_m2, ylim = c(-1.5,2))
abline(a = 0,b = 1)
plot(y_test,Y_pron_m3, ylim = c(-1.5,2))
abline(a = 0,b = 1)
plot(y_test,Y_pron_m4, ylim = c(-1.5,2))
abline(a = 0,b = 1)
```














